name: ghostfolio
services:
  ghostfolio:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_REPO_NAME}:${APP_VERSION}
    container_name: ghostfolio
    restart: unless-stopped
    init: true
    logging:
      driver: awslogs
      options:
        awslogs-group: ghostfolio-logs
        awslogs-region: ${AWS_REGION}
        awslogs-stream: ghostfolio-logs-stream
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - ../.env
    ports:
      - 3333:3333
    depends_on:
      # redis:
      #   condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: ghostfolio-nginx-logs
        awslogs-region: ${AWS_REGION}
        awslogs-stream: nginx-logs-stream
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ec2-user/certbot/www:/var/www/certbot
      - /home/ec2-user/certbot/conf:/etc/letsencrypt
    command: sh -c "nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /home/ec2-user/certbot/www:/var/www/certbot
      - /home/ec2-user/certbot/conf:/etc/letsencrypt


  # redis:
  #   image: docker.io/library/redis:alpine
  #   container_name: gf-redis
  #   restart: unless-stopped
  #   user: '999:1000'
  #   cap_drop:
  #     - ALL
  #   security_opt:
  #     - no-new-privileges:true
  #   env_file:
  #     - ../.env
  #   command:
  #     - /bin/sh
  #     - -c
  #     - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
  #   healthcheck:
  #     test:
  #       ['CMD-SHELL', 'redis-cli --pass "$${REDIS_PASSWORD}" ping | grep PONG']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # postgres:
  #   image: docker.io/library/postgres:15-alpine
  #   container_name: gf-postgres
  #   restart: unless-stopped
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - CHOWN
  #     - DAC_READ_SEARCH
  #     - FOWNER
  #     - SETGID
  #     - SETUID
  #   security_opt:
  #     - no-new-privileges:true
  #   env_file:
  #     - ../.env
  #   healthcheck:
  #     test:
  #       ['CMD-SHELL', 'pg_isready -d "$${POSTGRES_DB}" -U $${POSTGRES_USER}']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

# volumes:
#   postgres:
