name: Build Docker image & release to Amazon ECR
on:
  push:
    branches:   
      - 'main' 
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs: 
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
        id-token: write
        contents: write   # for draft release

    env: 
        COMMIT_SHA: ${{ github.sha }}
        AWS_REGION: 'il-central-1'
        AWS_ROLE_ARN: 'arn:aws:iam::103002841798:role/GitHub-Actions-ECR-Role'
        AWS_ECR_REPO: 'study/task3.2.5'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ghostfolio/ghostfolio
      #     tags: |
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}

      - name: Set Image URI
        run: |
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.AWS_ECR_REPO }}" >> $GITHUB_ENV
          echo "github ref_name: ${{ github.ref_name }}"

      - name: Docker bild and tag
        run: |
          RELEASE_VERSION=${{ github.ref_name }}    
          docker build -t ${IMAGE_URI}:${COMMIT_SHA} .
          docker tag ${IMAGE_URI}:${COMMIT_SHA} ${IMAGE_URI}:${RELEASE_VERSION}

      - name: Docker push image to Amazon ECR
        run: |
          RELEASE_VERSION=${{ github.ref_name }}
          echo "IMAGE URI: ${IMAGE_URI}"
          docker push ${IMAGE_URI}:${COMMIT_SHA}
          docker push ${IMAGE_URI}:${RELEASE_VERSION}
 
      - name: Docker tag and push "latest" version to Amazon ECR
        if:  github.ref_name == 'main'
        run: |
          docker tag ${IMAGE_URI}:${COMMIT_SHA} ${IMAGE_URI}:latest
          docker push ${IMAGE_URI}:latest

      - name: Create draft GitHub release
        if: startsWith(github.ref_name, 'v4')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true


